# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=2.8.0+1.21.11
maven_group=de.dafuqs
archives_base_name=paginatedadvancements

# Dependencies
fabric_api_version=0.140.0+1.21.11
cloth_config_version=21.11.151
modmenu_version=17.0.0-alpha.1