# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Minecraft
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.9
minecraft_version_range=[1.21.9,)

# Parchment Mappings https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05

# https://neoforged.net/
neoforge_version=21.9.16-beta
neoforge_version_range=[21.9.16-beta,)
loader_version_range=[4,)

# Mod Properties
mod_version=2.7.0+1.21.9
mod_group=de.dafuqs
mod_id=paginatedadvancements
mod_name=paginatedadvancements
mod_license=MIT
mod_authors=DaFuqs
mod_description=Advancement Screen, but better

# Dependencies
cloth_config_version=20.0.148