# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Minecraft
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)

# Parchment Mappings https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

# https://neoforged.net/
neoforge_version=21.11.13-beta
neoforge_version_range=[21.11.12-beta,)
loader_version_range=[4,)

# Mod Properties
mod_version=2.8.0+1.21.11-neoforge
mod_group_id=de.dafuqs
mod_id=paginatedadvancements
mod_name=Paginated Advancements
mod_license=MIT
mod_authors=DaFuqs
mod_description=Advancement Screen, but better
issue_tracker_url=https://github.com/DaFuqs/PaginatedAdvancements/issues
display_url=https://github.com/DaFuqs/PaginatedAdvancements